version: '3'
services:
  backend:
    image: back-cours-igor
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
