version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: "mongo"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME="${mongodbuser}"
      - MONGO_INITDB_ROOT_PASSWORD="${mongodbpassword}"
      
    volumes:
      - './dockervolume/mongodb:/data/db'
    ports:
      - 27017:27017
